language: java
notifications:
  email: false
jdk:
- openjdk11
install: echo 'Run Maven Tests'
script:
- mvn clean install -Dmaven.javadoc.skip=true -B -V
#after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
  - travis
cache:
  directories:
  - "$HOME/.m2/repository"
