language: java
notifications:
  email: false
jdk:
- openjdk11
stages:
- compile
- test
- deploy
jobs:
  include:
  - stage: compile
    script:
    - mvn clean compile -DskipTests -Dmaven.javadoc.skip=true -B -V
  - stage: test
    script:
    - mvn clean test -Dmaven.javadoc.skip=true -B -V
  - stage: deploy
    script:
    - echo "Deploy stage.."
branches:
  only:
  - master
  - travis
cache:
  directories:
  - "$HOME/.m2/repository"
